### ISSUE TITLE
Pouvoir changer d'unitée de temps pour le dry hopping

### ISSUE THREAD

**Issue by bibitte** [314r/joliebulle#127]
Bonjour,

En dry hopping l'unité reste la minutes ça serai pratique de pouvoir changer l'unité pour le passer en jour ce qui collerai à la réalité.

**Comment by flagos** [comment]
Made a pull request in that way. Let's see.

**Comment by 314r** [comment]
Thanks flagos, but it won't work as expected. Time units should be in minutes in beerxml. 
In that case, we can save time in minutes in the TIME tag, and time in days in DISPLAY_TIME.

**Comment by flagos** [comment]
Oh, I didn't pay attention to that. 

I went through http://www.beerxml.com/beerxml.htm and you're right for the time units. The field DISPLAY_TIME is not mandatory. I don't really like the way to double store the same information just for display but it's not a big deal.

Anyway, I will do it in 2 separate commit so that you can choose if you want to have the DISPLAY_TIME or not.
